### PR TITLE
refactor(supervisor): refactored this.configuration.format

### PR DESCRIPTION
**Pull request by Samantha-uk**
In the latest version of Yarn, the previously deprecated `configuration.format` has been removed, this PR refactors supervisor to use `formatUtils.pretty`, the yarn suggested replacement for `configuration.format` .

Unfortunately, at present, the code will not compile.
Typescript is reporting errors `Argument of type 'string' is not assignable to parameter of type 'null'.ts(2345)` when formatting PATH items, for example in:
```
formatUtils.pretty(this.configuration,
            relativePath,
            formatUtils.Type.PATH
```

VSCode is incorrectly reporting that the method requires a null for the `value` argument.
image

VSCode correctly reports the method signature as `value: string|null` when used in the yarn repo
image

I suspect that the root cause is somewhere in the yarn.build configuration of typescript, but I have (_as yet_) been unable to pinpoint it.

A workaround (_that seems to illicit no ill effects_) is to comment out the following code.
```
    PATH: {
        pretty: (configuration: any, val: string) => string;
        json: (val: string) => any;
    };
```
in `formatUtils.d.ts`, lines 80:83

This PR also has added a few method return values that lint had raised as issues.

### CODE REVIEW

**Comment by ojkelly** [comment]
Thanks for getting this draft together. 

we might need to update yarn in this repo to the latest as well for those types?

**Comment by Samantha-uk** [comment]
> Thanks for getting this draft together.
> 
> we might need to update yarn in this repo to the latest as well for those types?

The refactor (barring the typescript errors mentioned) seemed to work OK with both v2.4.0 and `set version from sources`.

I did try upgrading typescript to latest release (as well as some ancillary packages like eslint etc) but the problem seemed to persist.  I'd be happy to take another stab at bringing all the dependencies up to date  (as a separate PR).

**Comment by oliversalzburg** [comment]
Just FYI, because I didn't check existing PRs, I also worked on fixing this and also ran into the exact same issue. https://github.com/oliversalzburg/yarn.build/commit/54ddc677089f9e85ad21a8a758462d236c7c3d24

I [asked for guidance on Discord](https://discord.com/channels/226791405589233664/226793713722982400/796370616835768340), but no solution was immediatly apparent.

**Comment by Samantha-uk** [comment]
I added a specific test (locally) in my yarn berry repo and VSCode/TS had no issues with it ... I suspect that somewhere in the yarn.build config we've something that is causing this ... but I cannot figure out what it is!

**Comment by oliversalzburg** [comment]
Excellent call! I believe this may have something to with it in the `package.json`:
```json
 "resolutions": {
    "typescript": "^3.8.3"
  },
```

**Comment by oliversalzburg** [comment]
I have a branch with updated development dependencies at https://github.com/ojkelly/yarn.build/pull/68 btw. I'll probably wait for other PRs to be merged before I investigate further.

**Comment by Samantha-uk** [comment]
I'd started a similar and also trying to set all the configuration parameters to mirror those used by yarn berry ... I believe there is mileage in that but I did not manage to complete the journey (ie I still saw the TS error).

**Comment by oliversalzburg** [comment]
This must be a problem with the berry typings IMHO. It reproduces in isolation: https://www.typescriptlang.org/play?ts=4.1.3#code/CYUwxgNghgTiAEIB2BXAtvAKgTwA4IG8BYAKHnPgAUBBTACXgF54AiG+lgGlIF9TRIsBGAD2SAM4AXeJJhQJAMxEw04gFzxiZCuzoatFQ-FxxJk7BoAUopAoCWAcxRzJdsRvnZO8AG5QIGlIwdkgOAJRMAHzwQSEOANykRhQAVuLu8JZ+ATGycRGM0Z6J2uQ8JeX84NBwMngI1BAQmHKKyqpMdfgiCjKt4koq4iUCNQjm+PAAyiLOYCAAPJjRzJiIAB6SyMDi8ADWINg98I3N-YMdAPxUsFBoIFsw4gunLfID7eIA2pgAul8AcjSYgBv0iXwADL94AAfeCoJrwQJ5UKw+EoJolCYITAACzs4gAkuIAHIYiCdGZzRY4fAAOl0kXiQA

**Comment by Samantha-uk** [comment]
Awesome investigation!
As a followup (in case there was some subtlety being missed) I tried same approach with the contents of formatUtils.d.ts from berry ... showed the same thing as you demonstrated.  [playground](https://www.typescriptlang.org/play?#code/PTAEDMEMGsFNQM4HsC28BGsBOWCeoAXXAB1gQCIBYAKCNNAEkATWAOwNAF5ECsBLVgHMA3DTrwAMkgDGkAkixce-IaNol4AYSStwfQQFcscvjqUJeAkWI2gAImWn9i8xdwsrr6+gAVI06EhBWABRAA8CNgRTVnNLVRt6ACVYYgUOd3ivGlgwtKwOFmkAG0gseDYDFFAAFVsAbxpQZtAAOQB5AH0ACQZWmqVyDp6+mvIAGiaW1oBVCQlB2fmJqeaAZU12nxDBja2QleoWtoBBAFkd7iHzg8mjlqST1oBxS9ByR5fb1dAkkIAxEJ-VqaN4fAFAkIg773ZqzM4AISBixmiKBh2OPhONW6gyxOIxLRmSQWV2JEkJzROdjsITsg2ptLslN+ITO7QAanTBn92VzmXdjptaYNhTDjnZidiGO1WoNJY8ajLWiy1gwAFpgtWalkMWn9QZ6qFjQUtWkbJIMHw1dpJeUhC1Wm1JFkSdqabG2wZuj3Oll-NbtCQzJWynkOoMh5Us2nbVr6gZXWNQhMsrGaADSJ1enRCAA0alC1WGrumszn84XWsWVTQAL45PLpUBFUrlUCVaprIjFeCNWGgBFB+ncABM9cb+UKsBKZXg0h0FkQBmIU4Q2mKCgAXKB0EgkL3IKw1Lkpy2Z2354uOAgV2vuhosMUBNAEDu9wfYEe1K256AF6wS68EeCDgAoKBvqA-bHPCSJJDu0HHC0xDlAQRA7gAFABeiGMYBAxDuR64OMoAAG6QMUO6sFUmBYAAlFwAB8yhWGoSEtAAVsgrCYeRlGgNRKC0QxnDMURbEtHWEnNEa-QIT8xwobAaG4Jh2H6EYJg6IRrDEWRFE7swbAECJzEeKxCmcdxvEGYwLDsKZoDiT8Uk-D6nrwVBlnNEpKlqToOGafh2lObpJF8TuUiyK4jnmQkA7HFxIUYRFoBRXICiOc5A6uQO5qaJa1q2vJCXIah6GgFhAUaXhBGhXpqUOAgTh8C4mVMSx8Xsc0SU8ZVjWOM4MUddlxy5ccAaRqGrQld1oC+RVVW6DVWl9UR4W2Yhc3NCwzVDdu9iDa1rjSdtm7RQd6WuKAAA+AkGMUxSnWNsVZM9VnJalW3bbtLVtVgO5NX9J3eUh50ZQDaUyBDt33Y973NHWWW6ad41miEcYJrN3ULaplXqbhq06Q1m2g8c4OuJF0Mg6V7G-ftkNAwzCOgEjHVxV4c29TZ-HfXNFOXdTCgs8c9PHQdTPi1gLNs6J9Wo6dZbZiEuYFkWyrY+xuP+cthPBWtYX6fxfgBEEoQRFEMSvZ4LPc-1tkm4EwThJEgFWyNKMuadCrSrKmtIdr+PVXrdXrUbVE0dg1sWbToB2yltmCcJHu4ArPzaiE-uKeVeNLYFtUhWHqVJ1H7NvaD8fF5H9Ep2nA74t0Wdlcpi0E0FoeG6lHPR113WV7Z3e1179Y-hef7iKAJyPTUxiAWBWAQUo4hIOAhCz6B4EICeTYFOes7thPaxIEY0iwAAPDUzHcAMuSu0wCCgHAuAr5P0-r-Pi8APygH4xhoJEWAEBnynsUGeIEP4IAANo1AALqQIAOS9XgTAxikCAAMMDYbUUeqAHcHMsEPSepOZsv4D62BqCuXsF8OwW1YPfWothr4aCvqAcokAmA6GKPgSBR8T7n0viRWB28zykPgOAAwrBpD60IJQ-hNC74PzqKQRiGEP5yCUbAHcNQNrFAMJo0AvCsCnwvoxOiWjZEmOESQse7ZxGSOkZAVcXDuy4F7HnFa+sdzaF1u3HQJFIgRDwVkEi4BSiCEgi43sZjOpeFPNY-eYiJFSJiE5JxuANwKHcSHEK3j86rR0XooJngQngXURoLRtg7rdyKTHOJu9REQCSdI3G1Db5sHoRolRbcC59VyR4mIBT9GGOMQIiApSCAaK0bDapMSrH1JsYk+xKTcYSD4BYVptCOnMKyb43pwddmDMggwABkB0BUOGfwxijESkLzKaQKZVTglQUQKkMoMM6yf39ggV5eEFCfNmfWaJHM5nTgSY0pZZheobIUQw5RCddFDOPkYy5NyUB3P0QMR5nhonZTqaCy84LklmDRVgaAOyeleP2T06J31NAAAsZzQBqb3ZomgsBIAQJBYFPwACKeiLB1W5dQXKeK94Es7FDQQEhYCkVgMULyA4Qg4AUIMbA7KsAsgAOplFYFYQYAB3HVVhdS6CQIMAQYEYxrNkFgJggwmDWrKEwKgwqaDAAAFTuqaO6yeTA7W3lXM2ANZ556EAZaAAABpuQQ-w+DFAAQgCNLy0J6vkGG+ACBSDSD4HoWAdqUhTm9aAAQFgjynwAHTeuAMQ+ZYK7FEtiOwpgUgY1xoAWsO86QMLlCnDuAt6QSL1H-FS1arN-bdKJqAPp2TjyAp3KRJAfAmAgqgrlGguMMIRoJhG8YEbIDzTkHSndGjy0NzomoDdW7g47r3QeggR7d0NwjeemgNBeqbv3cQQ9x6NCnuxN0F91B323q-fem9T7ANAA)

and then I wondered about the validity of using Type as the enum name ... This [playground](https://www.typescriptlang.org/play?#code/PTAEDMEMGsFNQM4HsC28BGsBOWCeoAXXAB1gQFgAoI00ASQBNYA7A0AXkQKwEtmBzANxUa8ADJIAxpAJIsHLrwHDqJeAGEkzcD34BXLDJ5aFCbnyEi1oACJlJvYrPmczSy6toAFSJOiR+WABRAA8CFgRjZlNzZStaACVYYjk2V1iPKlgQlKw2JkkAG0gseBY9FFAAMTkUGQAVawBvKlA20AA5AHkAfQAJOg76hQAibv7B+pGAGlb2joBVMTFRxeWZubaAZXUuryDRnb2gjcp2zoBBAFkDzjHrk9mz9oSLjoBxW9AR14-HzdACSCVSCQI66i+P2BoKC4P+zzaiyuACFQasFijQadzl4LvU+qNcfjse0FgkVncyWISW0LjYbEEbKM6QybDTAUErl0AGqM0ZArm8tlPc67BmjMXw842Ml4uhdDqjGWveryjrsrZ0ABakM1OvZdAZQ1GhthUxF7QZOwSdC89S6CSVQWttvtCXZYi66jxDtGnu9bvZQK2XTEC1VCv5ztD4bV7IZ+w6RuGdwTsOT7Nx6gA0hdPj0ggANeqwzWRu5Z3P5osljpl9VUAC+WRyqVABWKpVA5UqWyIhXgLQRoGRoaZnAATE2W7l8rAiiV4JItGZEHpiLOEJpCnIAFygdBIJADyDMFTZWft+edpcrtgIdebvpqLCFPjQBD7w-H2CnlQdxdQGXZhV24U8EHAWpP1AIdziRVEEn3WDznaYhSgIIh9wACmAnR9EMAgon3U9cGmUAADdIEKfdmAqTAsAASg4AA+RQLBUFD2gAK2QZhsMo6jQFolB6KY9hWJIjj2kbKS2lNIYkIBc40NgDDcGw3DdAMIwtGI5hSIoqj90YFgCDE1i3HYpTuN4-ijPoJhWHM0BJIBGSAX9H1EJg6y2hUtSNK0PDtMI3SXP0siBP3CRpGcZzLLiYdzh4sKsKi0AYpkORnNc4d3OHK11BtO0HUUpLUPQzDQBwoKtIIojwoM9K7AQBweCcbKWLYxLOLaFK+Oq5r7EcOKuty858vOYMYwjDoyt60B-KqmrtDqnSBpIyL7OQha2iYVqRr3Wxhva5xZN2ndYqOzLnFAAAfIS9EKQpzom+KMlemzUvSnbdv2tqOqwfcWoBs7fJQy6sqBjKpCh+7Huez62kbHL9POybLSCRNk3m3qlvU6rNPw9a9Ka7bwfOSHnGi2GwfKzj-sO6GQaZpHQBRrqEo8Bb+rswTfoWqnrtpuQ2fORnTqOlnJawNmOfExr0fOys8yCAti1LNVcc4-HAtW4nQo2iLDMEnw-ACYIwgiKJ3vcNnecG+yzf8QJQnCECbbGtG3PO5U5QVbWUN1wnaoNhrNpNmi6OwW2rPp0AHbS+zhNEr3cCVgE9SCQPlMqgmVuC+qwoj9KU5jzmPvBxPS+jxi04z4ciT6HOKtU5aiZC8PjfSrnY563rq-s3v659pt-2vQDRFAC5nvqQwQMgrAUAQBRRCQcBCHniCoPPVs8ivBcuynrYkAMSRYAAHnqVjOGGbJ3YYFe4Fwdfp9nrfF+X0AAH5QB8Qw0DhCwAgC+M9Chz3Ap-BAABteoABdaBAByfqiC4HMWgQABjgfDWiz1QD7i5jgp6L0ZxtgAkfaw9R1wDivt2K2zBH6gEaLQW+agb6gFKJABgWhCj4GgSfM+l9r5kXgbvS85D4DgD0MwSQhtCDUKEXQh+K9mGwGYlhT+DQ1D7nqFtQoehYD7gEVgc+V9mIMR0QosxYiyETy7FImRcjIAbl4X2XAA4C5rUNvuTQ+tO5aDIuEMIBCMhkXAMUfg0E3EDgsd1DwF5bGH0kdI2RUQXIuNwNuOQniw5hV8YXdaeiDEhPcGE2oWjSA6OsA9XuJS44JP3hIiAKS5H41offFgjDVHqI7kXAa+SvFRCKYY0AxjTHCIgOUggqidHw1qXEmxjS7HJMcWk-GYgeBmHafQrpbCcn+P6aHA5wzoJ0CAZAdANCxlCOYsxMpS8KkjOGDU0JMFEDJBKHDRs39A4IA+QROQPyFlNliVzRZc4knNNWSYfq2zlFML2QJYpozT4mJufcuo0ztFMLmRkWJuUGkQpvFC1JJg6hYGgPsvpPijl9Nib9dQAALec0A6n9zaOoLASAEDQTBQCAAigYswDU+WUHyoSg+xKeww34GIWA5FYCFB8sOIIOA5CjGwFyrA7IADqJRmAWFGAAd31RYA02gkCjD4JBeMmzpBYAYKMBgdqSgMBGNOSgwAABUXrWheungwR1D4NxtmDZeRehBmWgAAAY7n4FUHghQgEIGje8jChrZCRvgAgUgkgeA6FgI6pIs4-WgD4GYU858AB0frgCkKWZChxpLohcIYBIeNiagFbEfKkLCpRZz7mLakMiTQgK0vWuzQOvSSagAGbks8IL9zkSQDwBg4KYL5SoPjLC0aibRumNGyAi0ZCMv3dUKZqiq1NwYiobdu7Q77sPceggp6D1N2jTeqgVB+o7qPcQE9Z6agPKxaQK9eI+ifsoD+p9-6X2PvfZBoAA) is with a different name ... and the problem seems to go away.

**Comment by oliversalzburg** [comment]
I brought this up again on the Discord. arcanis said he would change the type structure so that it compiles to a TSD that doesn't have this problem. It's apparently a [know issue](https://github.com/microsoft/TypeScript/issues/35329).

Let's hope it'll land soon 😊

**Comment by Samantha-uk** [comment]
> I brought this up again on the Discord. arcanis said he would change the type structure so that it compiles to a TSD that doesn't have this problem. It's apparently a [know issue](https://github.com/microsoft/TypeScript/issues/35329).
> 
> Let's hope it'll land soon 😊

I was wrong, simply changing the name does not correct the issue. [playground](https://www.typescriptlang.org/play?#code/PTAEDMEMGsFNQM4HsC28BGsBOWCeoAXXAB1gQFgAoI00ASQBNYA7A0AXkQKwEtmBzANxUa8ADJIAxpAJIsHLrwHDqJeAGEkzcD34BXLDJ5aFCbnyEi1oACJlJvYrPmczSy6toAFSJOiR+WABRAA8CFgRjZlNzZStaACVYYjk2V1iPKlgQlKw2JkkAG0gseBY9FFAAZVRYAgALCyDChHgAbypQLtAAOQB5AH0ACToegBUFACJ+4dGxyYAaTu6egFUxMSm1jcXlrqr1Pq8gqYOjoN3Kbt6AQQBZE85p+4ulq+6Em56AcUfQSc+P1ee1ACSCADEgmCeuo-gCIVCgjDge8ums7gAhKFbVaYqGXa5eG5jIZTIkkgndVYJTZPaliSldG42GxBGxTZmsmyM0FBO59ABqbKmYP5Qu5b2uh1ZU2lKOuNmpxLofR6U0VnzGKp6PKqdAAWnC9YaeXRWeMpmakfNJd1WQcEnQvGM+gl1UEHU6XQkeWI+upia6pn6A96eWCqn0xKstaqRR6ozHtTzWcceuaJk9U0iMzyieoANI3X4DIIADTGSL1cae+aLJfLlZ61Z1VAAvlkcqlQAViqVQOVKlUiIV2iCMVH2ZwAEztzu5fKwIoleCSLRmRB6YgLhCaQpyABcoHQSCQo8gzBU2QXPaXfdX67YCC3O6GaiwhT40AQR5PZ9gF4qL2K6gGuzAbtwF4IOAcgoD+oAdKivS4liCRHoh1zXMQpQEEQR4ABRgTo+iGAQURHheuALKAABukCFEezAVJgWAAJQcAAfIoFgqJh3QAFbIMwBF0QxoBMSgLHsewXGUbx3RtvJXRWuM6EglhOF4aAhFaMRBhGFoFHMFRtH0UejAsAQ0lcW4PHqQJQkiWZ9BMKw1mgHJIKKSCIaBmhCH2V02F1FpOnaLo+lkYZHnGdRolHhI0jOO5tlxEh1yCdF+HxaAiUyHI7meUh3lIfa6iOs6rpqel3TBbhuAEUREWkeRMUmTldgIA4PBOAVnHcWlfFdJlwnaR19iOMl-VFdcJXXBGiaxj01VDaAdWhU1JEGaNlFxc5GGrd0TBdZNh62BNPXOEph37klZ15c4oAAD7iXohSFNds0pRkn0OVlOUHYdt4nZdZ2dd1vVYL9fG3flWAJVIcPPa973Q6AbaFcZ11zXaQRphmK1DetDXaZtkWtbtpliYDN2I84CN3VDgWYcdEP0+dIOQ2jGP9alHirSNTnU8z1yw+zD1yGj1ys6d8Mc2zkvMzzMltdj111sWQSlhWVbaoTfHE41unNdtRntc5Ph+AEwRhBEUTfe4aOC2NFu+P4gShOE4H29NWNeddGrKqq+uYYbpPG1tUU7bFVOMcx2AO3ZNXDY5LtiRJUm+7gasgsaQQhxpIUk2FektdFlM5RnCe8z9zPO9lzlV2xWc50h5JDAXtWacXZNl9H5tiXzieDUN9c5UPLf++2QF3iBoigDc71jIY4EwVgcEKKISDgIQK-QbBCBXl2eS3su-bzzUBiSLAAA8YxcZwEzZF7DAIKAcC4NvC9L3va8bwA-KAHwhg0DhCwAgG+i9CjLygn-BAABtMYABdeBAByEaqCkEcXgQABiQcjJi71QBHj5gQt6H15zdmAufawYwtyjjvgOW2zBX7VFqA0JoLR4CcBqKAxoAhmitAfqAUokAGBaEKPgeBl8sDXzvhxaiyCj43mofAcAehmCSCjoQeht8n7MNYbwuo-D+CCNgBxfCf8ZBjDUEeMYe1Ch6FgEeGRcj76sTsbo+RyiqGz37OozR2jIDbkkcOXAo4S4myjkeTQ4VI5RGouEMIJCMjUXAMUfg8Ewmjg8QNDw15fFnzURorRUQPIhNwHuOQkT4nRViaXbaDinEpPcGk2C1jbFsL4Zw1oyMh4tKTgUk+qiIAlO0cTRhz8WCGPYSYsxFje6m1APUqJCSqbNLYVfPRCiIDtIIDY0gdi+kZFyXzHxwy-HFMCWU4mYgeBmEmQYt+RiOECK4QsiO5M6mfL7k0sg5kwGQHQAw1x2ydlWP2Z0iYL0+bUTaIgZIJQkZtn-iHVoxAkXOFRXklQGMBlpSGYuIpozrkmBGo8l+zzZk9PMQ3RxzjNmyO2W09eHTDmgGhXk3JRVCWn3vCS0pJgUAlGgDUr5o0Vm1OYLkmm6h6hLmgPi-m3R1BYCQAgeCZyQQAEUnFmFalqygJVeUjMHLlJA-AxCwBorAQoAUkJBBwHIKY2A1VYB5AAdRKMwCwUwADu3qLCmm0EgKYfAYIpnudILADApgMCjSUBgkw5yUGAAAKjTZ0NNC8GCxufNubs+abxr0IPK0AAADfc-BwQ8EKGAhA5aEW4V9bIUt8AECkEkDwHQsBY1JAXFm0AfAzAXmvgAOizcAShFziUBMFdEMRDAJDVtrWAqoL5Uj4VKAuI8-bUhwtAj87a6MQ6LOicso9UdcW5JokgHgDBzlsDaCVKgxN8Lls2uWhY5bIBrRkPUL9XTjE0rHe3ViKg30fojl+n9f6GgwfbuW8DVAqAjXfb+jF8HqIvLmVw0DxIhjIcoGh2DmGAPfsQ0RoAA)

**Comment by ojkelly** [comment]
In #88 a bunch of updates including this PR we're combined to get a release compatible with Yarn 3 out.

While the main issue of this PR persists, I'm just going to side-step it so it can unblock us.

Just released is this for yarn 3 `yarn plugin import https://yarn.build/latest`.

With yarn 2 available at `yarn plugin import https://yarn.build/v2`.

Thanks for your help in digging into the issue.

**Pull request closed without merging**
