### PR TITLE
Bail out early on error #78

### PR DESCRIPTION
**Pull request by lodmfjord**
This pull request is a total rewrite of the last pull request.  I decided it would be nice to keep the correct logs even though we bail.

Changes from previous pull request: 

* Instead of force quitting, we mark all incomplete tasks as skipped.
* Get all child processes and kill them. Mark those who were killed as skipped.

The code was tested on Linux, MacOS and Windows.

### CODE REVIEW

**Comment by lodmfjord** [comment]
It would have been nicer to keep a state of the pids in the class and then terminate those, but I didn't find a way to do that from reading the yarn docs. 

Thus I created this new helper function directory: terminate.

I did this solely, so it is easier to replace it in the future.

………

Weird race conditions on some machines, so checking again for child processes was necessary.

**Comment by lodmfjord** [comment]
Great. I think I have resolved all issues.

I also moved bail from folders to root:

```
   folders: {
      input: ".",
      output: "build",
    },
    bail: false,
    maxConcurrency: 8,
 ```

**Comment by lodmfjord** [comment]
OK forgot to change the tests.

**Comment by ojkelly** [comment]
> Should probably move this test to typescript later on so errors like these are spotted :)

yeah, the whole repo is setup for ts jest tests, so this was probably just missed in all of that.

This is looking great, I'm going to merge it in, and will cut a new release tomorrow.

**Pull request merged**
